AOC2020_HOME_DIRECTORY := $(PWD)/2020

run:
	cd $(AOC2020_HOME_DIRECTORY) && pipenv run python aoc2020/day$(DAY).py

run-all:
	cd $(AOC2020_HOME_DIRECTORY) && pipenv run python aoc2020/day$(DAY).py

test:
	cd $(AOC2020_HOME_DIRECTORY) && pipenv run python -m pytest
