# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: python@3.7.9-slim-stretch
        with:
          command: |
                 pip install pipenv
                 cd 2020 && pipenv install -d  # Install all dependencies, including development ones
    
      - name: Test
        uses: python@3.7.9-slim-stretch
        with:
          command: cd 2020 && make test # Run custom `test` command defined in the `[scripts]` block of Pipfile
